### ISSUE TITLE
Allow fixed positions for control fields

### ISSUE THREAD

**Issue by tomascohen** [bywatersolutions/koha-plugin-csv2marc#12]
For example, if you wanted to have this on your CSV:

008_date | 008_place | 100_author | 245_title
---------|--------------|------------|----------
s1997      |  nyu               | Your Author | Your Title

it would be great that it could be specified like:

```
008:
  - column: 0
     position: 6
  - column:1
     position: 15
```
