### ISSUE TITLE
Add a way to mark subfield as mandatory for field creation

### ISSUE THREAD

**Issue by tomascohen** [bywatersolutions/koha-plugin-csv2marc#18]
Using this plugin extensively yielded this particular use case:

- You have a bunch of barcodes
- All holdings share the callnumber, shelving location, etc

The current plugin behaviour requires that all subfields need to be empty in order not to create a field i.e. if some subfield is not empty, the field is created.

Now look at this sample spreadsheet:

callnum      | barcode_1 | barcode_2 
-----------|-----------|------------
something | asd            | sdf             
other          | xcv            |  

it would be great if we could define:

```
952_1:
  - column: 0
    subfield: p
  - column:1
    subfield: o
    required: true
952_2:
  - column: 0
    subfield: p
  - column:2
    subfield: o
    required: true
```
This way, if some rows have a different amount of 952 occurences, we don't need to do some spreadsheet magic to multiply the columns with its consequent mapping configuration escalation.
