### ISSUE TITLE
Fields are not mapping correctly

### ISSUE THREAD

**Issue by esthermel** [bywatersolutions/koha-plugin-csv2marc#35]
Note: Tested in 24.05 and 23.11. Not sure if there is something wrong in the configuration or example import file.

To Replicate:
1. Setup the plugin with:

020:
  - subfield: a
    column: 1
100:
  - subfield: a
    column: 3
245:
  - subfield: a
    column: 2

2. Setup a corresponding spreadsheet (example attached) and import
3. Check the batch and preview the records. See the fields are not mapped correctly. (example image attached).
[Example_import.csv](https://github.com/user-attachments/files/17248073/Example_import.csv)
![mapped_record](https://github.com/user-attachments/assets/ca38164d-fb69-42f2-8ac9-b01664539102)

**Comment by tomascohen** [comment]
Hi, the reason is not working for you is because column numbers start in zero (it would be more intuitive it was 1). The right mapping for your example would be:

```yaml
020:
    subfield: a
    column: 0
100:
    subfield: a
    column: 2
245:
    subfield: a
    column: 1
```

Hope it helps!
