### ISSUE TITLE
Support for indicators

### ISSUE THREAD

**Issue by tomascohen** [bywatersolutions/koha-plugin-csv2marc#6]
We should support indicators. A possible syntax:

```
245:
  - subfield: a
    column: 2
  - indicator: 1
    column 3
  - indicator: 2
    column: 4
```
